---
hero_image: images/rpg.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Escape the maze
description: Design and code your own maze escape text-based game.
original_url: https://codeclubprojects.org/en-GB/python/rpg
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2025-01-02
steps:
- title: Step 1
- title: Step 2
  completion:
  - engaged
- title: Step 3
- title: Step 4
- title: Step 5
- title: Step 6
- title: Step 7
- title: Step 8
  completion:
  - internal
  - external
- title: Step 9
  challenge: true